Console.WriteLine('файл для дебага');
int a = 0;
int b = 20;
Console.WriteLine('введите значение числа a');
Console.Readline(a);
Console.WriteLine(b);
a += 10;
b += 10;
Console.WriteLine(b);
Console.WriteLine('новое значение числа a:', a);